services:
  php-base:
    build: docker/php
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    networks:
      uitdatabank-backend:
        aliases:
          - io.uitdatabank.local
          - data.uitdatabank.local
    healthcheck:
      test: curl http://127.0.0.1:80/
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailpit:
        condition: service_healthy

  php:
      container_name: php.uitdatabank
      extends:
          service: php-base
      ports:
          - '8000:80'

  php-xdebug:
      container_name: php-xdebug.uitdatabank
      extends:
          service: php-base
      profiles:
          - xdebug
      build:
          context: docker/php
          args:
              ENABLE_XDEBUG: "true"
      environment:
          XDEBUG_MODE: debug
          XDEBUG_CONFIG: client_host=host.docker.internal
      ports:
          - '8001:80'  # Explicitly override to port 8001

  mysql:
    image: 'bitnami/mysql:8.0'
    container_name: mysql.uitdatabank
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - 'udb3-mysql:/bitnami/mysql/data'
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    networks:
      uitdatabank-backend:
        aliases:
          - mysql.uitdatabank.local
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: 'redis:alpine'
    container_name: redis.uitdatabank
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'udb3-redis:/data'
    networks:
      uitdatabank-backend:
        aliases:
          - redis.uitdatabank.local
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      retries: 3
      timeout: 5s

  rabbitmq:
    image: public.ecr.aws/y2o7k5u2/udb3/rabbitmq:latest
    hostname: 'rabbitdocker'
    container_name: rabbitmq.uitdatabank
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      uitdatabank-backend:
        aliases:
          - rabbitmq.uitdatabank.local
    healthcheck:
      test: [ 'CMD', 'rabbitmqctl', 'node_health_check' ]
      retries: 3
      timeout: 5s

  mailpit:
    image: axllent/mailpit:latest
    hostname: 'mailpit'
    container_name: mailpit.uitdatabank
    restart: unless-stopped
    volumes:
      - 'udb3-mailpit:/data'
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      uitdatabank-backend:
        aliases:
          - mailpit.uitdatabank.local
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8025/api/v1/info"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  uitdatabank-backend:
    name: uitdatabank
    driver: bridge

volumes:
  udb3-redis:
    driver: local
  udb3-mysql:
    driver: local
  udb3-mailpit:
    driver: local
